#spring.application.name=Shop-Application
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
spring:
  application:
    name: Shop-Application
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create